import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Provider";
import MobileMenu from "@/components/navbar/MobileMenu";
import { AuthProvider } from "../contexts/AuthContext";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const ClientSideLayout = dynamic(() => import("@/components/ClientSideLayout"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <ClientSideLayout>
              {children}
            </ClientSideLayout>
            <MobileMenu />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
